# Exploring dunder methods in Mojo

In [5]:
from DunderArray import DunderArray
from python import Python

np = Python.import_module("numpy")

x = DunderArray(np.sin(np.arange(0, 6, 0.1)))
y = DunderArray.rand(x.numel)

z = x**3 + 3 * x - x / 5.0 + 0.3 + y**2

error: Expression [5] wrapper:4:1: no viable expansions found
fn __lldb_expr__5(inout __mojo_repl_arg: __mojo_repl_context__):
^

Expression [5] wrapper:6:28:   call expansion failed - no concrete specializations
    __mojo_repl_expr_impl__(__mojo_repl_arg)
                           ^

Expression [5] wrapper:10:1:     no viable expansions found
def __mojo_repl_expr_impl__(inout __mojo_repl_arg: __mojo_repl_context__) -> None:
^

Expression [5] wrapper:19:26:       call expansion failed - no concrete specializations
  __mojo_repl_expr_body__()
                         ^

Expression [5] wrapper:13:3:         no viable expansions found
  def __mojo_repl_expr_body__() -> None:
  ^

<unknown>:0:           could not simplify operator get_alignof(!lit.unresolved, #kgen.target<triple = "aarch64-apple-macosx14.2.1", arch = "apple-m1", features = "+aes,+complxnum,+crc,+dotprod,+fp-armv8,+fp16fml,+fullfp16,+jsconv,+lse,+neon,+pauth,+ras,+rcpc,+rdm,+sha2,+sha3", data_layout = "e-m:o-i64:64-i128:1

In [2]:
plt = Python.import_module("matplotlib")

plt = Python.import_module("matplotlib.pyplot")
plt.plot(z.to_numpy(), "r")
plt.show()

error: /Users/jack/src/devrel-extras/blogs/2402-mojo-dunder/DunderArray.mojo:340:5: do not know how to resolve the signature of this decl!
    fn to_numpy(self) raises -> PythonObject:
    ^

error: /Users/jack/src/devrel-extras/blogs/2402-mojo-dunder/DunderArray.mojo:71:5: do not know how to resolve the signature of this decl!
    fn __neg__(self) -> Self:
    ^

error: /Users/jack/src/devrel-extras/blogs/2402-mojo-dunder/DunderArray.mojo:74:5: do not know how to resolve the signature of this decl!
    fn __pos__(self) -> Self:
    ^

error: /Users/jack/src/devrel-extras/blogs/2402-mojo-dunder/DunderArray.mojo:77:5: do not know how to resolve the signature of this decl!
    fn __invert__(self) -> Self:
    ^

error: /Users/jack/src/devrel-extras/blogs/2402-mojo-dunder/DunderArray.mojo:94:5: do not know how to resolve the signature of this decl!
    fn __lt__(self, other: Self) -> Bool:
    ^

error: /Users/jack/src/devrel-extras/blogs/2402-mojo-dunder/DunderArray.mojo:97:5: do not kno

In [ ]:
arr1 = DunderArray(5)
arr2 = DunderArray(1, 2, 3, 4, 5)
print(arr1)
print(arr2)

[0.0  0.0  0.0  0.0  0.0]
Length:5, DType:float64
[1.0  2.0  3.0  4.0  5.0]
Length:5, DType:float64


In [ ]:
arr = DunderArray.rand(5)
print("Original:", arr)
arr_copy = arr

print()
print("Copy:", arr_copy)

Original: [0.1736  0.7514  0.8249  0.7530  0.3190]
Length:5, DType:float64

Copy: [0.1736  0.7514  0.8249  0.7530  0.3190]
Length:5, DType:float64


In [ ]:
fn test_move():
    var arr = DunderArray(2, 4, 6, 8)
    print(arr)
    var arr_moved = arr ^
    print(arr_moved)
    # print(arr) #<-- ERROR: use of uninitialized value 'arr'


test_move()

[2.0  4.0  6.0  8.0]
Length:4, DType:float64
[2.0  4.0  6.0  8.0]
Length:4, DType:float64


In [ ]:
arr = DunderArray(1,2,3,4,5)
print(arr[3])

4.0


In [ ]:
arr = DunderArray(1, 2, 3, 4, 5)
arr[3] = 100
print(arr)

[1.0  2.0  3.0  100.0  5.0]
Length:5, DType:float64


In [ ]:
arr = DunderArray(1, 2, 3, 4, 5)
print(+arr)
print(arr)
print(-arr)

arr_bool = DunderArray[DType.bool](True, False, True)
print(~arr_bool)

[1.0  2.0  3.0  4.0  5.0]
Length:5, DType:float64
[1.0  2.0  3.0  4.0  5.0]
Length:5, DType:float64
[-1.0  -2.0  -3.0  -4.0  -5.0]
Length:5, DType:float64
[False  True  False]
Length:3, DType:bool


In [ ]:
arr1 = DunderArray.rand(100)
arr2 = DunderArray.rand(100)

print("Norm of arr1:", (arr1**2)._reduce_sum())
print("Norm of arr2:", (arr2**2)._reduce_sum())

print("Comparing the squared euclidean norm of arr1 and arr2")
print("__lt__: arr1 <  arr2:", arr1 < arr2)
print("__le__: arr1 <= arr2:", arr1 <= arr2)
print("__eq__: arr1 == arr2:", arr1 == arr2)
print("__ne__: arr1 != arr2:", arr1 != arr2)
print("__gt__: arr1 >  arr2:", arr1 > arr2)
print("__ge__: arr1 >= arr2:", arr1 >= arr2)

Norm of arr1: [29.1796]
Length:1, DType:float64
Norm of arr2: [33.7959]
Length:1, DType:float64
Comparing the squared euclidean norm of arr1 and arr2
__lt__: arr1 <  arr2: True
__le__: arr1 <= arr2: True
__eq__: arr1 == arr2: False
__ne__: arr1 != arr2: True
__gt__: arr1 >  arr2: False
__ge__: arr1 >= arr2: False


In [ ]:
arr1 = DunderArray.rand(5)
arr2 = DunderArray(100, 100, 100, 100, 100)

# Normal  and in-place
print(arr1 + 100.0)
print(arr1 + arr2)

# Reflected
print(100.0 + arr1)

# In-place
arr1 += 100.0
print(arr1)

[100.1038  100.6068  100.2352  100.3556  100.5682]
Length:5, DType:float64
[100.1038  100.6068  100.2352  100.3556  100.5682]
Length:5, DType:float64
[100.1038  100.6068  100.2352  100.3556  100.5682]
Length:5, DType:float64
[100.1038  100.6068  100.2352  100.3556  100.5682]
Length:5, DType:float64


In [ ]:
arr1 = DunderArray.rand(5)
arr2 = DunderArray(100, 100, 100, 100, 100)

# Normal and in-place
print(arr1 - 100.0)
print(arr1 - arr2)

# Reflected
print(100.0 - arr1)

# In-place
arr1 -= 100.0
print(arr1)

[-99.4521  -99.5073  -99.8977  -99.8914  -99.6529]
Length:5, DType:float64
[-99.4521  -99.5073  -99.8977  -99.8914  -99.6529]
Length:5, DType:float64
[99.4521  99.5073  99.8977  99.8914  99.6529]
Length:5, DType:float64
[-99.4521  -99.5073  -99.8977  -99.8914  -99.6529]
Length:5, DType:float64


In [ ]:
arr1 = DunderArray.rand(5)
arr2 = DunderArray(100, 100, 100, 100, 100)

# Normal and in-place
print(arr1 * 100.0)
print(arr1 * arr2)

# Reflected
print(100.0 * arr1)

# In-place
arr1 *= 100.0
print(arr1)

[82.3512  88.6479  70.7390  18.0723  84.8782]
Length:5, DType:float64
[82.3512  88.6479  70.7390  18.0723  84.8782]
Length:5, DType:float64
[82.3512  88.6479  70.7390  18.0723  84.8782]
Length:5, DType:float64
[82.3512  88.6479  70.7390  18.0723  84.8782]
Length:5, DType:float64


In [ ]:
arr1 = DunderArray.rand(5)
arr2 = DunderArray.rand(5)

# Normal and in-place
print(arr1 @ arr2)

# Verify
print((arr1 * arr2)._reduce_sum())

# In-place
arr1 @= arr2
print(arr1)

[1.1172]
Length:1, DType:float64
[1.1172]
Length:1, DType:float64
[1.1172]
Length:1, DType:float64


In [ ]:
arr1 = DunderArray.rand(5)
arr2 = DunderArray(10, 10, 10, 10, 10)
val = 10.0

print(arr1)
print(arr1 / val)
print(arr1 / arr2)
print(val / arr1)
arr2 /= val
print(arr2)

error: Expression [34]:3:7: cannot implicitly convert 'FloatLiteral' value to 'Int' in assignment
val = 10.0
      ^~~~

error: Expression [34]:6:11: ambiguous call to '__truediv__', each candidate requires 1 implicit conversion, disambiguate with an explicit cast
print(arr1/val)
      ~~~~^~~~

/Users/shashank/projects/demos/mojo-drafts/mojo_dunder/DunderArray.mojo:147:5: candidate declared here
    fn __truediv__(self, s: Scalar[dtype])->Self:
    ^

/Users/shashank/projects/demos/mojo-drafts/mojo_dunder/DunderArray.mojo:150:5: candidate declared here
    fn __truediv__(self, other: Self)->Self:
    ^

expression failed to parse (no further compiler diagnostics)

In [ ]:
arr1 = DunderArray.rand(5) * 100.0
arr2 = DunderArray(10, 10, 10, 10, 10)
val = 10.0

print(arr1)
print(arr1 // val)
print(arr1 // arr2)
print(val // arr1)
arr2 //= val
print(arr2)

In [ ]:
arr1 = DunderArray.rand(5) * 100.0
arr2 = DunderArray(10, 10, 10, 10, 10)
val = 10.0

print(arr1)
print(arr1 % val)
print(arr1 % arr2)
print(val % arr1)
arr2 %= val
print(arr2)

In [ ]:
arr_pow = DunderArray(1, 2, 3, 4, 5)
let val: Int = 2

print(arr_pow)
print(arr_pow**val)
arr_pow **= val
print(arr_pow)

In [ ]:
arr_shift = DunderArray[DType.int32](1, 2, 3, 4, 5)

print(arr_shift)
print(arr_shift << 2)
arr_shift <<= 4
print(arr_shift)
print(arr_shift >> 2)
arr_shift >>= 4
print(arr_shift)

In [ ]:
arr_bool1 = DunderArray[DType.bool](1, 1, 1, 1)
arr_bool2 = DunderArray[DType.bool](1, 0, 1, 0)

print("AND:")
print(arr_bool1 & arr_bool2)
arr_bool1& = arr_bool2
print(arr_bool1)

print("OR:")
print(arr_bool1 | arr_bool2)
arr_bool1 |= arr_bool2
print(arr_bool1)

print("XOR:")
print(arr_bool1 ^ arr_bool2)
arr_bool1 ^= arr_bool2
print(arr_bool1)

In [ ]:
arr = DunderArray.rand(100)

print(len(arr))
print(int(arr))
print(arr)